### ISSUE TITLE
Query by Genre?

### ISSUE THREAD

**Issue by petersem** [phillipj/node-plex-api#110]
Is there any way to query media by genre? I was trying to use the criteria option that you provided however, there can be multiple genres for a given title. I could parse the data once returned, but I'd prefer if there were a more elegant way.

Thanks!

btw. Great API!

**Comment by phillipj** [comment]
Good question!

It's been a while since I had fun with the responses coming from the Plex Server, and don't even have a Plex installation available these days to check it out.

Any chance you have the raw response you could share with us? That might raise ideas with regards to using todays query functionality or be very valuable for discussing plausible tweaks to plex-api' code.

**Comment by petersem** [comment]
Here you go. This is just one title from my anime library.  (truly it's for my daughter!!) :)

```json
{
  size: 40,
  allowSync: true,
  art: '/:/resources/show-fanart.jpg',
  identifier: 'com.plexapp.plugins.library',
  librarySectionID: 17,
  librarySectionTitle: 'Anime',
  librarySectionUUID: '013db2aa-a580-40dd-a4d1-5a6c086a9152',
  mediaTagPrefix: '/system/bundle/media/flags/',
  mediaTagVersion: 1618841647,
  nocache: true,
  thumb: '/:/resources/show.png',
  title1: 'Anime',
  title2: 'All Shows',
  viewGroup: 'show',
  viewMode: 65592,
  Metadata: [
{
  ratingKey: '185158',
  key: '/library/metadata/185158/children',
  guid: 'com.plexapp.agents.thetvdb://280329?lang=en',
  studio: 'Tokyo MX',
  type: 'show',
  title: 'Akame ga Kill!',
  contentRating: 'TV-MA',
  summary: "In a fantasy world, fighter Tatsumi sets out for the Capitol to earn money for his starving village, and finds a world of unimaginable corruption, all spreading from the depraved Prime Minister who controls the child Emperor's ear. After nearly becoming a victim of this corruption himself, Tatsumi is recruited by Night Raid, a group of assassins dedicated to eliminating the corruption plaguing the Capitol by mercilessly killing those responsible.",
  index: 1,
  rating: 8,
  year: 2014,
  thumb: '/library/metadata/185158/thumb/1614494571',
  art: '/library/metadata/185158/art/1614494571',
  banner: '/library/metadata/185158/banner/1614494571',
  theme: '/library/metadata/185158/theme/1614494571',
  duration: 1500000,
  originallyAvailableAt: '2014-07-07',
  leafCount: 24,
  viewedLeafCount: 24,
  childCount: 1,
  addedAt: 1614473673,
  updatedAt: 1614494571,
  Genre: [ { tag: 'Action' }, { tag: 'Adventure' } ],
  Role: [
    { tag: 'Hitomi Nabatame' },
    { tag: 'Yuu Asakawa' },
    { tag: 'Katsuyuki Konishi' }
  ]
}
```

**Comment by petersem** [comment]
@phillipj also, this is what i'm using your library for.
[petersem/Posterr GitHub ](https://github.com/petersem/posterr)
[petersem/poster Docker Hub](https://hub.docker.com/r/petersem/poster)

**Comment by phillipj** [comment]
Nice @petersem 👍🏻 

At first glance it indeed seems like there needs to be some `.find()` adjustments needed to be able to match on the what your responses include inside `Metadata.Genre`. Especially two things comes to mind:

1. It's a child field beneath `Metadata`, which needs to be handled specifically
2. The `Metadata.Genre` (and `Metadata.Role` for that matter) is an array of objects as you mentioned, not plain strings as `.find()` were targeted at finding when it was introduced

The test samples from old Plex server format (pre v1.3 IIRC) gives an impression what it was meant to find initially:

https://github.com/phillipj/node-plex-api/blob/a95ca02faffd6fb5cb0236d4303103b95359edf5/test/samples/library/sections.json#L17

..plain string fields per item and verified in the following test:

https://github.com/phillipj/node-plex-api/blob/a95ca02faffd6fb5cb0236d4303103b95359edf5/test/find-test.js#L64-L68

---

I'll be totally honest with you as I don't want to give you false expectations; I will not personally be spending time getting these improvements in place. Because of (1) I have very limited time to devote to open source these days and (2) I don't need this myself.

That does not mean it can't happen. This is an open source project after all, contributions are more than welcome for those who wants to give it a shot.

**Comment by petersem** [comment]
All good mate. I appreciate the response. It's a good point if it belongs in our API or is an implementation thing.  I'll have a think and may put a PR together. That is, if i can find time from my own open-source projects. :)

**Comment by petersem** [comment]
i'll close for now
