### ISSUE TITLE
MediaContainer.result?

### ISSUE THREAD

**Issue by markaswift** [phillipj/node-plex-api#74]
Hi,

In your example you use result.friendlyName, I find I need to use result.MediaContainer.friendlyName?

Is this because of a recent change to the result, or am I missing something?

**Comment by Hellowlol** [comment]
Plex changed some json responses in the API in Pms 1.3

**Comment by markaswift** [comment]
Makes sense. I'm new to node, could you possibly tell me how I can get a token using this module?

**Comment by phillipj** [comment]
@Hellowlol is right probably right. I've been noticed about breaking changes in the data format released in PMS 1.3.x. We'll probably have to handle those format changes in this npm package somehow -- I haven't had the time to dig into it yet.

Refs https://github.com/phillipj/node-plex-api/issues/75

**Comment by markaswift** [comment]
Excellent... I've worked around it.

I'd appreciate some help grabbing a token, add in manually to the websocket address.

I use this to authenticate:

`function loginPlex(credentials) {
    console.log('[LOGIN] Plex notifier attempting login...')
    console.log('[LOGIN] Login credentials:')
    console.log(credentials)
    plexClient = new PlexAPI({
        hostname: credentials.plexIP,
        username: credentials.plexUsername,
        password: credentials.plexPassword,
        port: credentials.plexPort
    })
    return plexClient.query('/').then(function(result) {
        console.log('[CANDY] Server Name: ' + result.MediaContainer.friendlyName)
        console.log('[CANDY] Server Version: ' + result.MediaContainer.version)
        return Promise.resolve()
    })
}`

How can I also grab a token?

**Comment by phillipj** [comment]
> How can I also grab a token?

You'd have to use [plex-api-credentials](https://github.com/phillipj/node-plex-api-credentials) directly, which emits the `token` event.

```js
const PlexAPI = require('plex-api');
const credentials = require('plex-api-credentials');

const userAndPass = credentials({
    username: 'yourUsername',
    password: 'aSecretPassword'
});

const client = new PlexAPI({
    hostname: '192.168.0.1',
    authenticator: userAndPass
});

userAndPass.on('token', function(token){
    // possibly cache retrieved token here?
});
```

**Comment by markaswift** [comment]
That's awesome,

I added plex-api via NPM and can see that plex-api-credentials is included? I'm therefore assuming I don't need to save it as a separate module?

If so, how can I include it, this didn't seem to work?

`const PlexAPICredentials = require('plex-api-credentials') `

I'm still learning, thank you for the help.

**Comment by phillipj** [comment]
> I'm therefore assuming I don't need to save it as a separate module?

Yes, you should. If your code requires anything directly, as with `plex-api-credentials` in this case, it should *always* be listed in your `package.json`.

You're right about `plex-api` is installing credentials, that's use behind the scenes to get the trivial username/password support that the majority might need. And depending on which npm version you have installed, and other packages listed in your `package.json`, the credentials package might actually be possible for you to `require()` directly. This is called a transitive dependency, which is something you should never rely on cause you never know what version you'll get, or if that package actually will be available at all. Easily fixed by specifying it in your `package.json` 😃
